# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9nBnSgZ-MF-Gc5LPkCM-r84VZVxw_Pe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data= pd.read_csv("/content/train.csv")

data.head()

data.tail()

data.index

data.shape

data.size

data.columns

data.describe()

data.info()

data.info()

data = data.drop_duplicates()
data.head(8)

data['Age'] = pd.to_numeric(data['Age'], errors='coerce')
data['Fare'] = pd.to_numeric(data['Fare'], errors='coerce')

summary_stats = data.describe()
print(summary_stats)

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(data['Age'].dropna(), kde=True)
plt.title('Age Distribution')
plt.subplot(1, 2, 2)
sns.countplot(data['Sex'])
plt.title('Gender Distribution')
plt.show()

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.countplot(data['Pclass'])
plt.title('Pclass Distribution')
plt.subplot(1, 2, 2)
sns.countplot(data['Embarked'])
plt.title('Embarked Distribution')
plt.show()

survival_rate_by_class = data.groupby('Pclass')['Survived'].mean()
survival_rate_by_sex = data.groupby('Sex')['Survived'].mean()

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.barplot(x=survival_rate_by_class.index, y=survival_rate_by_class.values)
plt.title('Survival Rate by Pclass')
plt.subplot(1, 2, 2)
sns.barplot(x=survival_rate_by_sex.index, y=survival_rate_by_sex.values)
plt.title('Survival Rate by Sex')
plt.show()

plt.figure(figsize=(9, 6))
sns.boxplot(x='Survived', y='Age', data=data)
plt.title('Survival by Age')
plt.xticks([0, 1], ['Not Survived', 'Survived'])
plt.show()

data['FamilySize'] = data['SibSp'] + data['Parch']

sns.pairplot(data, vars=['Age', 'Fare', 'FamilySize'], hue='Survived')
plt.suptitle('Pair Plot of Age, Fare, and FamilySize')
plt.show()

plt.figure(figsize=(9, 6))
data['Title'] = data['Name'].str.extract(' ([A-Za-z]+)\.')
sns.countplot(data['Title'])
plt.title('Passenger Titles')
plt.xticks(rotation=45)
plt.show()

title_survival_rate = data.groupby('Title')['Survived'].mean()
plt.figure(figsize=(12, 5))
sns.barplot(x=title_survival_rate.index, y=title_survival_rate.values)
plt.title('Survival Rate by Title')
plt.xticks(rotation=45)
plt.show()

